version: '3'

volumes:
  mongodb:
    external: true
  configdb:
    external: true

volumes: {}

services:
    nginx:
        image: nginx:alpine
        ports: []
        volumes:
            - ./:/app
            - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            default:
                aliases: []
    php:
        image: webiny/php7:dev
        volumes:
            - ./:/app:delegated
        environment:
            XDEBUG_CONFIG: "remote_enable=0 remote_host=0.0.0.0"
        extra_hosts: []

    mongodb:
        image: mongo
        volumes:
            - mongodb:/data/db
            - configdb:/data/configdb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        ports: []
        command: mongod --smallfiles --logpath=/dev/null # --quiet
