version: '2'

volumes: {}

services:
    nginx:
        image: nginx:alpine
        ports: []
        volumes:
            - ./:/app
            - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            default:
                aliases: []
    php:
        image: webiny/php7:dev
        volumes:
            - ./:/app:delegated
        environment:
            XDEBUG_CONFIG: "remote_enable=0 remote_host=0.0.0.0"
        extra_hosts: []

    mongodb:
        image: mongo
        volumes:
          - ./data/db:/data/db
        ports: []
        command: mongod --smallfiles --logpath=/dev/null # --quiet
